# ==============================================================================
# ===
# === Buttons
# ===
# ==============================================================================

button:
  logout    : Esci

# ==============================================================================
# ===
# === Pages
# ===
# ==============================================================================

page:
  header:
    platform : Piattaforma
